using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace erp.Migrations
{
    /// <inheritdoc />
    public partial class AddMissingKanbanTables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Create KanbanLabels table if not exists
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""KanbanLabels"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""BoardId"" integer NOT NULL REFERENCES ""KanbanBoards""(""Id"") ON DELETE CASCADE,
                    ""Name"" character varying(50) NOT NULL,
                    ""Color"" character varying(7) NOT NULL DEFAULT '#6366F1',
                    ""IsActive"" boolean NOT NULL DEFAULT true,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW()
                );
                CREATE INDEX IF NOT EXISTS ""IX_KanbanLabels_BoardId"" ON ""KanbanLabels""(""BoardId"");
            ");

            // Add new columns to KanbanCards if they don't exist
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    -- AssignedUserId
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'KanbanCards' AND column_name = 'AssignedUserId') THEN
                        ALTER TABLE ""KanbanCards"" ADD COLUMN ""AssignedUserId"" integer REFERENCES ""AspNetUsers""(""Id"") ON DELETE SET NULL;
                    END IF;
                    
                    -- Priority
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'KanbanCards' AND column_name = 'Priority') THEN
                        ALTER TABLE ""KanbanCards"" ADD COLUMN ""Priority"" integer NOT NULL DEFAULT 0;
                    END IF;
                    
                    -- Color
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'KanbanCards' AND column_name = 'Color') THEN
                        ALTER TABLE ""KanbanCards"" ADD COLUMN ""Color"" character varying(7);
                    END IF;
                    
                    -- IsArchived
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'KanbanCards' AND column_name = 'IsArchived') THEN
                        ALTER TABLE ""KanbanCards"" ADD COLUMN ""IsArchived"" boolean NOT NULL DEFAULT false;
                    END IF;
                    
                    -- CompletedAt
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'KanbanCards' AND column_name = 'CompletedAt') THEN
                        ALTER TABLE ""KanbanCards"" ADD COLUMN ""CompletedAt"" timestamp with time zone;
                    END IF;
                END $$;
            ");

            // Create KanbanCardLabels table if not exists
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""KanbanCardLabels"" (
                    ""CardId"" integer NOT NULL REFERENCES ""KanbanCards""(""Id"") ON DELETE CASCADE,
                    ""LabelId"" integer NOT NULL REFERENCES ""KanbanLabels""(""Id"") ON DELETE CASCADE,
                    PRIMARY KEY (""CardId"", ""LabelId"")
                );
                CREATE INDEX IF NOT EXISTS ""IX_KanbanCardLabels_LabelId"" ON ""KanbanCardLabels""(""LabelId"");
            ");

            // Create KanbanComments table if not exists
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""KanbanComments"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""CardId"" integer NOT NULL REFERENCES ""KanbanCards""(""Id"") ON DELETE CASCADE,
                    ""AuthorId"" integer NOT NULL REFERENCES ""AspNetUsers""(""Id"") ON DELETE CASCADE,
                    ""Content"" character varying(4000) NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
                    ""UpdatedAt"" timestamp with time zone,
                    ""IsEdited"" boolean NOT NULL DEFAULT false
                );
                CREATE INDEX IF NOT EXISTS ""IX_KanbanComments_CardId"" ON ""KanbanComments""(""CardId"");
                CREATE INDEX IF NOT EXISTS ""IX_KanbanComments_AuthorId"" ON ""KanbanComments""(""AuthorId"");
            ");

            // Create KanbanCardHistories table if not exists
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""KanbanCardHistories"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""CardId"" integer NOT NULL REFERENCES ""KanbanCards""(""Id"") ON DELETE CASCADE,
                    ""UserId"" integer NOT NULL REFERENCES ""AspNetUsers""(""Id"") ON DELETE CASCADE,
                    ""Action"" integer NOT NULL,
                    ""Description"" character varying(500) NOT NULL DEFAULT '',
                    ""OldValue"" character varying(1000),
                    ""NewValue"" character varying(1000),
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW()
                );
                CREATE INDEX IF NOT EXISTS ""IX_KanbanCardHistories_CardId"" ON ""KanbanCardHistories""(""CardId"");
                CREATE INDEX IF NOT EXISTS ""IX_KanbanCardHistories_UserId"" ON ""KanbanCardHistories""(""UserId"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""KanbanCardHistories"";");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""KanbanComments"";");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""KanbanCardLabels"";");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""KanbanLabels"";");
            
            migrationBuilder.Sql(@"
                ALTER TABLE ""KanbanCards"" DROP COLUMN IF EXISTS ""AssignedUserId"";
                ALTER TABLE ""KanbanCards"" DROP COLUMN IF EXISTS ""Priority"";
                ALTER TABLE ""KanbanCards"" DROP COLUMN IF EXISTS ""Color"";
                ALTER TABLE ""KanbanCards"" DROP COLUMN IF EXISTS ""IsArchived"";
                ALTER TABLE ""KanbanCards"" DROP COLUMN IF EXISTS ""CompletedAt"";
            ");
        }
    }
}
